### ISSUE TITLE
Bad data due to stepper backlash

### ISSUE THREAD

**Issue by rockjim** [Sardau/Sardauscan#9]
I find that because the stepper has some backlash in it, the first couple scan passes often have some bad data.  It seems like the easiest way to fix this would be to have the stepper take a few steps (or more) before the first scan to make sure to get even forward tension on the scanning bed.

**Comment by Sardau** [comment]
noted

**Comment by kariangel** [comment]
hello my friend i need to change  stepper (28BYJ-48) whith stepper 1.8 deg  200 steps
what i must change in firmware
thanks

**Comment by Sardau** [comment]
Hello it depend of your stepper driver and your motor :

in the firmware,

configuration.h
#define HALFSTEP 8
#define REVOLUTION_STEP 4072
#define STEP_BY_MINMOVE 4  

and in firmware.ino
AccelStepper stepper1(HALFSTEP, motorPin1, motorPin3, motorPin2, motorPin4);

for the specific values of the constructor of the accelstepper, see your wiring and the help of the accelstepper library.

**Comment by kariangel** [comment]
Bonjour sardau et merci pour la réponse
J'ai le même type de driver que vous avez utilisé mais il peut aller
jusqu'à 2 A j'ai utilisé un moteur pas a pas de 1.5A\200pas  avec une
alimentation externe je voudrait modifié votre firmware pour avoir 200
pas/tour et non 2048 pas/tour
Merci mon amis

**Comment by Sardau** [comment]
REVOLUTION_STEP est le nombre de step reel  (physique) pour faire un tour.

STEP_BY_MINMOVE est le rapport entre les step physique et logique.

le nombre de step logique  (ceux que le soft windows voit) => REVOLUTION_STEP/STEP_BY_MINMOVE;

Donc si par exemple tu as un moteur qui fait 200 pas par rotation, que ton stepper a 16 micosteps 
=> REVOLUTION_STEP = 200*16
mais si tu veux que le soft n'en voit que 200 => tu fixe STEP_BY_MINMOVE  a 16 (car REVOLUTION_STEP /STEP_BY_MINMOVE  donne 200).

Cela dit, je ne vois pas pourquoi tu veux limiter le nombre de step pour un tour. garde le maximum pour ton hardware dans le firmware. et choisi plustot la "precision" dans la tache de scan (en gros cela change le Nbr de step entre 2 images)

**Comment by kariangel** [comment]
Merci sardau
En faite je veut améliorer la qualité de scan et je veut utilisé un moteur
pas a pas plus stable pour avoir une rotation fluide
En tous cas bravo tu a fait du bon travail
Salut

Le 6 févr. 2017 10:50, "Fabio Ferretti" <notifications@github.com> a écrit :

REVOLUTION_STEP est le nombre de step reel (physique) pour faire un tour.

STEP_BY_MINMOVE est le rapport entre les step physique et logique.

le nombre de step logique (ceux que le soft windows voit) =>
REVOLUTION_STEP/STEP_BY_MINMOVE;

Donc si par exemple tu as un moteur qui fait 200 pas par rotation, que ton
stepper a 16 micosteps
=> REVOLUTION_STEP = 200*16
mais si tu veux que le soft n'en voit que 200 => tu fixe STEP_BY_MINMOVE a
16 (car REVOLUTION_STEP /STEP_BY_MINMOVE donne 200).

Cela dit, je ne vois pas pourquoi tu veux limiter le nombre de step pour un
tour. garde le maximum pour ton hardware dans le firmware. et choisi
plustot la "precision" dans la tache de scan (en gros cela change le Nbr de
step entre 2 images)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Sardau/Sardauscan/issues/9#issuecomment-277633469>, or mute
the thread

**Comment by Sardau** [comment]
c'est le nombre de pas total qui est important pour la resolution 200 au lieu de 1000+(4072/4) => 5 fois moins de sample par tour.

**Comment by kariangel** [comment]
Je vais utilisé le micro pas +réducteur
Es que l'arduino gère le micro pas?
Je vais utilisé le moteur 200 pas et je vais programmer l'arduino en micro
pas
Seulement j'ai un problèmes avec la compilation du firmware
Salut

Le 6 févr. 2017 11:34, "Fabio Ferretti" <notifications@github.com> a écrit :
>
> c'est le nombre de pas total qui est important pour la resolution 200 au
lieu de 1000+(4072/4) => 5 fois moins de sample par tour.

**Comment by kariangel** [comment]
bonjour sardau
j'ai utilisé le scanner le résultat n'est pas vraiment fameux mais dans l'ensemble cava
je voulais juste savoir pour quoi tu a utiliser 4 lasers au lieu d'un?
j'ai constater que le soft fait un balayage de 10 degré et je voudrais augmenté la précision 
c'est a dire faire un balayage de 1 ou 2 degré 
comment je peut faire sa?
salut

**Comment by Sardau** [comment]
4 laser = 4 vue differentes du meme profil ( mais le temps additionnel n'est pas fois 4 ;) ) Pour les objets plus complexe cela aide car un laser ne voit pas ce qu'un autre voit.

Pour la presision du scan, il faut cliquer sur les petit engrenages a coté de la tache "scan".
 (chanque tache a ses propres options : dans la colone de gauche tu change le default, dans celle de droite uniquement pour le process couran)

il faut aussi allez dans "tune" et modifier le threshold pour avoir une ligne bien bien net. (tu peux aussi allez dans les config de la camera pour modifier l'exposition, cela aide pas mal)


un scan brut n'est pas top, 

perso je fait un "scan" 
puis un "laser" ou "angle", ( moyenne par angle ou sur les lasers "a la meme position")
puis un "build mesh"

**Comment by kariangel** [comment]
bonsoir sardau
je n'arrive pas a enregistrer le scan je fait le save mais il ya rien le soft n'enregistre pas
merci

**Comment by Sardau** [comment]
pour sauver le scan, il faut ajouter une tache de sauvegarde.

Si tu n'as pas de tache de "build mesh", tu ne peut sauver que dans des formats de "point cloud".

si tu as une tache qui reconstruit le modele (build mesh) tu peux sauvegarder dans un format d'objet mesh (stl et obj).

 perso je te conseil de faire un process scan + save .SAR
comme cela tu sauvegarde ton scan dans un format interne au soft.

ensuite tu peut faire un autre process ou tu load le sar puis tu ajoutes differentes taches pour toi essayer.

cela te permet de jouer avec les differentes taches sans devoir scanner a chaque fois. 

c'est plus rapide quand tu tatonne dans les taches ;)

**Comment by kariangel** [comment]
bonsoir  sardau
je voudrais savoir comment je peut augmenter la précision puisque tu la limité sur ton soft a 100
je voudrais l'augmenté a 300 ou 400 
100 c'est peut l'angle est trop grand le scanner ne capte pas toutes les formes
merci

**Comment by Sardau** [comment]
le 100 est un pourcentage : a 100 il tourne par le nombre de step minimum que le firmware de l'arduino renseigne.

**Comment by kariangel** [comment]
Bonjour sardau
J'ai vue sur youtube un type a utiliser hardware sardauscan et software
horis scan c'est possible
Merci

Le 19 févr. 2017 09:10, "Fabio Ferretti" <notifications@github.com> a
écrit :

le 100 est un pourcentage : a 100 il turne par le nombre de step minimum
que le firmware de l'arduino renseigne.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Sardau/Sardauscan/issues/9#issuecomment-280903418>, or mute
the thread

**Comment by Sardau** [comment]
je sais qu'une personne a modifier le firmware du horus pour le faire fonctionner avec le hardware du sardauscan. 

ps: je lui ai demander sur instructable de partager ses modifications, mais je n'ai pas eut de réponse.
Si tu as des liens vers ce firmware, cela m’intéresse d'essayé ;)

**Comment by kariangel** [comment]
Pour quoi ne pas modifier le soft sardauscan pour faire un balayage en
continue c'est a dire le moteur tourne en continue et en petite vitesse et
le laser allumer en continue et le soft enregistre le résultat comme sa on
aura un résultat meilleur. Le même système que David scan
Merci

Le 21 févr. 2017 09:40, "Fabio Ferretti" <notifications@github.com> a
écrit :

**Comment by Sardau** [comment]
Si le moteur tourne on ne peut pas prendre 5 images a la même position. (une de référence et 1 par lazer. voir "How does it work?" dans http://www.instructables.com/id/Build-a-30-laser/ )

la détection des lasers en plein jour est déjà difficile a "tuner" pour beaucoup de personnes, mais si en plus on a pas d'image de référence, ce serait encore plus compliqué..

Cela dit, si tu connais une autre technique, libre a toi de faire ta propre tache de scan via un plugin.
